#########################
# NAME: keepalived      #
# AUTHOR: DesertRatz    #
# CREATED: 2024/11/01   #
# (C) 2022-2025         #
#########################

vrrp_instance VI_1 {
		state BACKUP
		interface eth0
		track_interface {
			eth0
		}
		virtual_router_id 6
		priority 100
		advert_int 1
		unicast_src_ip XXX.XXX.XXX.XXX
		unicast_peer {
		XXX.XXX.XXX.XXX
}

authentication {
		auth_type PASS
		auth_pass SUPER-PASSWORD
}

virtual_ipaddress {
		XXX.XXX.XXX.XXX/24
	}
}