###########################
# NAME: Docker Pihole     #
# AUTHOR: DesertRatz      #
# CREATED: 2026/05/01     #
# (C) 2022-2026           #
###########################

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2026.07.2 # Current (2026-0707)
    network_mode: host
    restart: unless-stopped # This determines the restart state for the container
    environment:
      TZ: "America/Los_Angeles" # We will set the TZ here. Default is "America/Los_Angeles"
      PIHOLE_UID: 1000 # Set to root if needed / default 1000
      PIHOLE_GID: 1000 # Set to root if needed / default 1000
      # We will set a password OR allow a random password here
      FTLCONF_webserver_api_password:
    tty: true
    stdin_open: true
    volumes: # Volumes store your data between container upgrades
      - /data/docker/pihole/pihole:/etc/pihole # Config directory
      - /data/docker/pihole/dnsmasq.d:/etc/dnsmasq.d # DNSmasq directory
      - /etc/hostname:/etc/hostname:ro # Access the hostname
    cap_add:
      - SYS_NICE
    deploy:
      resources:
        limits:
          cpus: 2.0 # RPi5 cpu safe buffer
          memory: 1g # RPi5 memory safe buffer
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"