###########################
# NAME: Proxmox ZFS conf  #
# AUTHOR: DesertRatz      #
# CREATED: 2023/11/14     #
# (C) 2022-2024           #
###########################

options zfs zfs_arc_min=1073741824 zfs zfs_arc_max=4294967296
